### ISSUE TITLE
"Connect on slack" CTA directs users to the "introductions" channel in Drawdown slack organization 

### ISSUE THREAD

**Issue by colleenskemp** [ProjectDrawdown/open-collaboratory#25]
Need:
As a user, I can connect to the Drawdown slack community from the homepage. When I click on the "connect on slack" I am sent to the "introductions" room in the Drawdown slack organization. 

Description:

See designs here: https://www.figma.com/file/hqCFFKf4aiA9An0yQsQilU/Collaboratory-(Chakra-UI-Figma-Kit)?node-id=1158%3A9294

1) Connect on slack: This is intended to build the Collaboratory community and get people connected. These folks should go to the #introductions room in the Drawdown Global Research Collaborative slack organization. 

Acceptance criteria: 
When user clicks on "connect on slack" they are directed to the introductions slack channel in Drawdown organization.

**Comment by colleenskemp** [comment]
@Chukslord1 - for the "connect on slack" CTA, users should be brought to the introductions slack room in the DGRC slack organization. Let me know if you have questions.

**Comment by eethann** [comment]
We can implement this ticket in 2 phases, since a simple Slack link is not possible (links expire): first create a form via Netlify's form function and then, optionally, Netlify's lambda function integration to call the slack invite endpoint to invite the guest (https://api.slack.com/methods/admin.users.invite).
